#!/bin/bash
export QIIME_CONFIG_FP=/data004/software/GIF/GIF/programs/qiime/qiime-1.7.0-release/../qiime_config
export LAPACK=None
export PYTHONPATH=/data004/software/GIF/GIF/programs/qiime/emperor-0.0.0-repository-567da32b/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/emperor-0.0.0-repository-567da32b/lib/:/data004/software/GIF/GIF/programs/qiime/qiime-galaxy-0.0.1-repository-5b980770/lib/:/data004/software/GIF/GIF/programs/qiime/qiime-1.7.0-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/qiime-1.7.0-release/lib/:/data004/software/GIF/GIF/programs/qiime/pprospector-1.0.1-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/matplotlib-1.1.0-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/pycogent-1.5.3-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/biom-format-1.1.2-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/ipython-latest-repository-e2a9fc09/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/sphinx-1.0.4-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/MySQL-python-1.2.3-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/mpi4py-1.2.2-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/setuptools-0.6c11-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/SQLAlchemy-0.7.1-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/numpy-1.5.1-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/gdata-2.0.17-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/pyzmq-2.1.11-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/cython-0.17-release/lib/python2.7/site-packages:/data004/software/GIF/GIF/programs/qiime/pynast-1.2-release/lib/python2.7/site-packages

export BLAS=None
export TEST_DB=1
export BLASTMAT=/data004/software/GIF/GIF/programs/qiime/blast-2.2.22-release/data
export QIIME=/data004/software/GIF/GIF/programs/qiime/qiime-1.7.0-release/./
export RDP_JAR_PATH=/data004/software/GIF/GIF/programs/qiime/rdpclassifier-2.2-release/rdp_classifier-2.2.jar
export PYCOGENT=/data004/software/GIF/GIF/programs/qiime/pycogent-1.5.3-release/./
export PYRO_LOOKUP_FILE=/data004/software/GIF/GIF/programs/qiime/AmpliconNoiseV1.27/Data/LookUp_E123.dat
export SEQ_LOOKUP_FILE=/data004/software/GIF/GIF/programs/qiime/AmpliconNoiseV1.27/Data/Tran.dat
export ATLAS=None

export PATH=/data004/software/GIF/GIF/programs/qiime/emperor-0.0.0-repository-567da32b/bin:/data004/software/GIF/GIF/programs/qiime/qiime-galaxy-0.0.1-repository-5b980770/scripts:/data004/software/GIF/GIF/programs/qiime/qiime-1.7.0-release/bin:/data004/software/GIF/GIF/programs/qiime/pprospector-1.0.1-release/bin:/data004/software/GIF/GIF/programs/qiime/biom-format-1.1.2-release/bin:/data004/software/GIF/GIF/programs/qiime/cython-0.17-release/bin:/data004/software/GIF/GIF/programs/qiime/ipython-latest-repository-e2a9fc09/bin:/data004/software/GIF/GIF/programs/qiime/python-2.7.3-release/bin:/data004/software/GIF/GIF/programs/qiime/infernal-1.0.2-release/bin:/data004/software/GIF/GIF/programs/qiime/vienna-1.8.4-release/.:/data004/software/GIF/GIF/programs/qiime/cdhit-3.1-release/.:/data004/software/GIF/GIF/programs/qiime/uclust-1.2.22-release/.:/data004/software/GIF/GIF/programs/qiime/blast-2.2.22-release/bin:/data004/software/GIF/GIF/programs/qiime/cytoscape-2.7.0-release/.:/data004/software/GIF/GIF/programs/qiime/rdpclassifier-2.2-release/.:/data004/software/GIF/GIF/programs/qiime/muscle-3.8.31-release/.:/data004/software/GIF/GIF/programs/qiime/parsinsert-1.0.4-release/.:/data004/software/GIF/GIF/programs/qiime/bwa-0.6.2-release/.:/data004/software/GIF/GIF/programs/qiime/fasttree-2.1.3-release/.:/data004/software/GIF/GIF/programs/qiime/cdbtools-10.11.2010-release/.:/data004/software/GIF/GIF/programs/qiime/mothur-1.25.0-release/.:/data004/software/GIF/GIF/programs/qiime/chimeraslayer-4.29.2010-release/ChimeraSlayer:/data004/software/GIF/GIF/programs/qiime/chimeraslayer-4.29.2010-release/NAST-iEr:/data004/software/GIF/GIF/programs/qiime/raxml-7.3.0-release/.:/data004/software/GIF/GIF/programs/qiime/rtax-0.983-release/.:/data004/software/GIF/GIF/programs/qiime/sourcetracker-0.9.5-release/.:/data004/software/GIF/GIF/programs/qiime/clearcut-1.0.9-release/.:/data004/software/GIF/GIF/programs/qiime/blat-34-release/.:/data004/software/GIF/GIF/programs/qiime/pynast-1.2-release/bin:/data004/software/GIF/GIF/programs/qiime/usearch-5.2.236-release:/data004/software/GIF/GIF/programs/qiime/usearch-6.1.544-release:/data004/software/GIF/GIF/programs/qiime/R-2.12.0-release/bin:/data004/software/GIF/GIF/programs/qiime/ghc-7.6.3-release/bin:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release/:/data004/software/GIF/GIF/programs/qiime/pplacer-v1.1.alpha14-Linux-3.2.0:/data004/software/GIF/GIF/programs/qiime/mothur-1.25.0-release:/data004/software/GIF/GIF/programs/qiime/gsl-1.15/gsl:/data004/software/GIF/GIF/programs/qiime/python-2.7.3-release/lib:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release:/data004/software/GIF/GIF/programs/qiime/gsl-1.15/lib:/data004/software/GIF/GIF/programs/qiime/ghc-7.6.3-release/bin:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release/:$PATH
export SOURCETRACKER_PATH=/data004/software/GIF/GIF/programs/qiime/sourcetracker-0.9.5-release/.
export LD_LIBRARY_PATH=/data004/software/GIF/GIF/programs/qiime/python-2.7.3-release/lib:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release:/data004/software/GIF/GIF/programs/qiime/gsl-1.15/lib:/data004/software/GIF/GIF/programs/qiime/ghc-7.6.3-release/bin:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release/
export LD_RUN_PATH=/data004/software/GIF/GIF/programs/qiime/python-2.7.3-release/lib:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release:/data004/software/GIF/GIF/programs/qiime/gsl-1.15/lib:/data004/software/GIF/GIF/programs/qiime/ghc-7.6.3-release/bin:/data004/software/GIF/GIF/programs/qiime/gmp-5.1.2-release/
